"""Leistungsrückmeldung

Revision ID: 01b7b9982170
Revises: 7b827f4cdbb0
Create Date: 2025-05-26 19:09:52.986282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b7b9982170'
down_revision = '7b827f4cdbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leistungs_rueckmeldung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('lernfeld_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('gespeichert_am', sa.DateTime(), nullable=True),
    sa.Column('thema', sa.String(length=255), nullable=False),
    sa.Column('rueckmeldung', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['lernfeld_id'], ['lernfeld.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leistungs_rueckmeldung')
    # ### end Alembic commands ###
