"""Initial schema with Lerngruppe + KursRueckmeldung

Revision ID: 7b827f4cdbb0
Revises: 
Create Date: 2025-05-19 21:10:56.518140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b827f4cdbb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lernfeld',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lerngruppe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('kurs_rueckmeldung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lernfeld_id', sa.Integer(), nullable=False),
    sa.Column('lerngruppe_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('phase', sa.String(length=20), nullable=False),
    sa.Column('thema', sa.String(length=255), nullable=False),
    sa.Column('gespeichert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lernfeld_id'], ['lernfeld.id'], ),
    sa.ForeignKeyConstraint(['lerngruppe_id'], ['lerngruppe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('spitzname', sa.String(length=100), nullable=True),
    sa.Column('lerngruppe_id', sa.Integer(), nullable=False),
    sa.Column('stufe', sa.Integer(), nullable=False),
    sa.Column('foerderbedarf', sa.Text(), nullable=True),
    sa.Column('foerderbedarf_massnahmen', sa.Text(), nullable=True),
    sa.Column('ziele', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lerngruppe_id'], ['lerngruppe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thema_llk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thema', sa.String(length=100), nullable=True),
    sa.Column('thema_notiz', sa.Text(), nullable=True),
    sa.Column('lernfeld_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lernfeld_id'], ['lernfeld.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('freiarbeit_eintrag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('lernfeld_id', sa.Integer(), nullable=True),
    sa.Column('thema_text', sa.Text(), nullable=True),
    sa.Column('gespeichert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lernfeld_id'], ['lernfeld.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kurs_teilnahme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rueckmeldung_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('anwesend', 'abwesend', name='status_enum'), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['rueckmeldung_id'], ['kurs_rueckmeldung.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thema_zuweisung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('lernfeld_id', sa.Integer(), nullable=False),
    sa.Column('thema_basistext', sa.String(length=255), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lernfeld_id'], ['lernfeld.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thema_zuweisung')
    op.drop_table('kurs_teilnahme')
    op.drop_table('freiarbeit_eintrag')
    op.drop_table('thema_llk')
    op.drop_table('person')
    op.drop_table('kurs_rueckmeldung')
    op.drop_table('lerngruppe')
    op.drop_table('lernfeld')
    # ### end Alembic commands ###
